server:
  port: 8090
  servlet:
    session:
      timeout: 120s
#    context-path: '/tools'

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ai-001
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
  mvc:
    async:
      request-timeout: 120s
  ai:
    openai:
      api-key: ${ai.token}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat #deepseek-reasoner  # 调用的哪个模型名称
      embedding:
        enabled: false
#deepseek-chat（V3）：适用于聊天机器人、智能客服、内容生成等，能够理解和生成日常对话内容。
#deepseek-reasoner（R1）：专为复杂推理任务设计，适合解决需要深度逻辑分析和推理的问题。


management:
  metrics:
    tags:
      application: ${spring.application.name}
      #app-version: '@project.version@'
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
