server:
  port: 8090
  servlet:
    session:
      timeout: 120s
#    context-path: '/tools'

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ai-001
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
  mvc:
    async:
      request-timeout: 120s
  ai:
    openai:
      api-key: ${ai.token}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner  # 调用的哪个模型名称
      embedding:
        enabled: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
      #app-version: '@project.version@'
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  default-flat-param-object: true
knife4j:
  enable: true
  setting:
    language: EN
    swagger-model-name: Response Entities